---
- hosts: 12.0.4.97
  become: true
  become_method: sudo 
  tasks:
  - name: Install packages
    apt: 
      name: ['apache2' , 'tree'] 
      state: latest
    when: ansible_distribution == 'Ubuntu'
